project:
  type: website

website:
  title: "Lester Wang"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects


  page-footer:
    right: "&copy; 2025, Lester Wang"

format:
  html:
    theme: cosmo
      - cosmo
      - brand
    css: styles.css
    toc: true
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em


execute: 
  freeze: auto
  